// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Product.Api.Data;

namespace Product.Api.Migrations
{
    [DbContext(typeof(ProductContext))]
    [Migration("20200613074033_seedproductsinprodApi")]
    partial class seedproductsinprodApi
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Product.Api.Models.Products", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImgUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "beatufil picture by:",
                            ImgUrl = "https://i.picsum.photos/id/150/200/300.jpg",
                            Name = "Photo1",
                            Price = 249.5,
                            Quantity = 0
                        },
                        new
                        {
                            Id = 2,
                            Description = "beatufil picture by:",
                            ImgUrl = "https://i.picsum.photos/id/200/200/300.jpg",
                            Name = "Photo2",
                            Price = 249.5,
                            Quantity = 0
                        },
                        new
                        {
                            Id = 3,
                            Description = "beatufil picture by:",
                            ImgUrl = "https://i.picsum.photos/id/225/200/300.jpg",
                            Name = "Photo3",
                            Price = 179.5,
                            Quantity = 0
                        },
                        new
                        {
                            Id = 4,
                            Description = "beatufil picture by:",
                            ImgUrl = "https://i.picsum.photos/id/240/200/300.jpg",
                            Name = "Photo4",
                            Price = 349.0,
                            Quantity = 0
                        },
                        new
                        {
                            Id = 5,
                            Description = "beatufil picture by:",
                            ImgUrl = "https://i.picsum.photos/id/199/200/300.jpg",
                            Name = "Photo5",
                            Price = 129.5,
                            Quantity = 0
                        },
                        new
                        {
                            Id = 6,
                            Description = "beatufil picture by:",
                            ImgUrl = "https://i.picsum.photos/id/175/200/300.jpg",
                            Name = "Photo6",
                            Price = 349.5,
                            Quantity = 0
                        },
                        new
                        {
                            Id = 7,
                            Description = "beatufil picture by:",
                            ImgUrl = "https://i.picsum.photos/id/270/200/300.jpg",
                            Name = "Photo7",
                            Price = 129.0,
                            Quantity = 0
                        },
                        new
                        {
                            Id = 8,
                            Description = "beatufil picture by:",
                            ImgUrl = "https://i.picsum.photos/id/300/200/300.jpg",
                            Name = "Photo8",
                            Price = 349.0,
                            Quantity = 0
                        },
                        new
                        {
                            Id = 9,
                            Description = "beatufil picture by:",
                            ImgUrl = "https://i.picsum.photos/id/284/200/300.jpg",
                            Name = "Photo9",
                            Price = 99.5,
                            Quantity = 0
                        },
                        new
                        {
                            Id = 10,
                            Description = "beatufil picture by:",
                            ImgUrl = "https://i.picsum.photos/id/198/200/300.jpg",
                            Name = "Photo10",
                            Price = 149.0,
                            Quantity = 0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
